In [1]:
##Deeplearning is subset of ML

In [2]:
  # A machine learning technique that learns features and tasks directly from data
    # Inputs run through "Neural Networks
    #Neural Networks have hidden layers"

In [3]:
## tensor basics

In [4]:
## Tensors are multi dimensionall arrays
## images can be written as arrays
# 8  it is a 0D array or a scalar
#[2,0,3] 1-D Tensor which is a vector which is made of 3 scalars
# [[1,2,0],[3,5,-1],[1,5,6],[2,3,8]] 2D  Tensor basically a mrtix


In [11]:
#! pip install tensorflow

## Constants

In [12]:
 import tensorflow as tf

In [13]:
tensor_zero_d = tf.constant(2)

In [14]:
print(tensor_zero_d)

tf.Tensor(2, shape=(), dtype=int32)


## Tensors 1D

In [17]:
tensor_1_D = tf.constant([2,0,-3,8,90.0])

In [18]:
print(tensor_1_D)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


## 2D tensor

In [20]:
tensor_2_D = tf.constant([[1,2,0],[3,5,-1],[1,5,6],[2,3,8]])

In [21]:
print(tensor_2_D)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [37]:
## to print shape of tensor we use
print(tensor_2_D.shape)
## to print dimensions
print(tensor_2_D.ndim)
#size of matrix
print(tf.size(tensor_2_D))

(4, 3)
2
tf.Tensor(12, shape=(), dtype=int32)


## Tensor operations

In [87]:
## conveert tensors to a higher dimensions

x= tf.constant([2,3,4,5])
print(x.shape)
print(tf.expand_dims(x,axis = 0))

(4,)
tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


In [88]:
## To lower dimension
tf.squeeze(tf.expand_dims(x,axis = 0),axis=0)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [90]:
## reshaping the dims
x_reshape = tf.constant([[3,5,6,6],[4,6,-1,2]])
print(x_reshape)
print(tf.reshape(x_reshape, [8,1]))

tf.Tensor(
[[ 3  5  6  6]
 [ 4  6 -1  2]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 3]
 [ 5]
 [ 6]
 [ 6]
 [ 4]
 [ 6]
 [-1]
 [ 2]], shape=(8, 1), dtype=int32)


In [24]:
#to typecast tensor into different dimensions use tf.cast()
cast_1d_int = tf.cast(tensor_1_D, dtype = tf.int16)
cast_1d_bool = tf.cast(tensor_1_D, dtype = tf.bool)
print(cast_1d_int)
print(cast_1d_bool)

tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [26]:
#tensor string
tensor_string = tf.constant(["hello world","Hi"])
print(tensor_string)
print()

tf.Tensor([b'hello world' b'Hi'], shape=(2,), dtype=string)



In [29]:
# comvert into numpy array
import numpy as np
np_array = np.array([1,2,4])
print(np_array)
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

[1 2 4]
tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [34]:
#eyetensor - prints identity matrix

eye = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [36]:
fill_tensor = tf.fill([3,4],5)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [42]:
##create random values
tf.random.normal(
    [3,2],
    mean=0.0,
    stddev = 1.0,
    dtype= tf.dtypes.float32,
    seed =None,
    name=None
)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 2.453166  , -0.57768387],
       [ 0.8282451 , -0.69618034],
       [ 0.6041455 , -0.45163187]], dtype=float32)>

In [45]:
tf.random.uniform(
    [3,5],
    minval=0,
    maxval = 1000,
    dtype= tf.dtypes.int32,
    seed =None,
    name=None
)

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[568, 994, 865, 262, 845],
       [327, 120, 818, 201, 943],
       [249, 158, 909, 481, 366]], dtype=int32)>

In [92]:
## concat tensors
t1= [[1,2,3],[4,5,6]]
t2 =[[7,8,9],[10,11,12]]
print(tf.concat([t1,t2],0)) ## to attach below
print(tf.concat([t1,t2],1)) ## to attach above

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


## Tensor Indexed

In [47]:
tensor_indexed= tf.constant([3,6,2,4,6,66,7])

In [50]:
print(tensor_indexed)
print(tensor_indexed[0:4:1])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)


In [49]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [52]:
## max value position
x_argmax = tf.constant([200,120,130,300,6])
print(tf.math.argmax(x_argmax))

tf.Tensor(3, shape=(), dtype=int64)


## Mathematical operations

In [53]:
#matmul is for matrix multiplication

In [63]:
x1 = tf.constant([[1,2,0],[3,5,1]])
x2= tf.constant([[1,2,0],[3,5,-1],[1,2,3]])

tf.linalg.matmul(x1,x2,transpose_a=False, transpose_b = False, adjoint_b = False,a_is_sparse= False, b_is_sparse = False, output_type =None, name= None)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 12, -2],
       [19, 33, -2]], dtype=int32)>

In [64]:
 #shortcut
print(x1@x2)

tf.Tensor(
[[ 7 12 -2]
 [19 33 -2]], shape=(2, 3), dtype=int32)


In [66]:
#Transpose of matrix
tf.transpose(x1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 5],
       [0, 1]], dtype=int32)>

In [74]:
## Band matrix
tensor_2_D = tf.constant([[1,2,0],[3,5,-1],[1,5,6],[2,3,8]], dtype = tf.float16)
tensor_2_D

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[ 1.,  2.,  0.],
       [ 3.,  5., -1.],
       [ 1.,  5.,  6.],
       [ 2.,  3.,  8.]], dtype=float16)>

In [72]:

tf.linalg.band_part(tensor_2_D,0,0)
### (Lower <0 or m-n <= lower) and (upper <0 or n-m <=upper)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float16)>

In [82]:
## Inverse of matrix
## only square matrix can have inverse
tensor_2d = tf.constant([[1,-2,0],[3,5,100],[1,5,6]],dtype = tf.float32)
tensor_2d_inv = tf.linalg.inv(tensor_2d)
tensor_2d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.7413249 , -0.01892742,  0.3154574 ],
       [-0.12933755, -0.00946371,  0.1577287 ],
       [-0.01577287,  0.01104101, -0.01735016]], dtype=float32)>

In [84]:
## product of two matrix is identity matrix
tensor_2d_inv@tensor_2d

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  1.7881393e-07,  2.8610229e-06],
       [ 1.4901161e-08,  1.0000000e+00,  1.0728836e-06],
       [ 0.0000000e+00, -3.7252903e-09,  9.9999988e-01]], dtype=float32)>

In [86]:
## Singular value decomposition
tf.linalg.svd(tensor_2d)

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([100.3663   ,   5.1059036,   1.2371687], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[-7.4980810e-04, -3.7569830e-01,  9.2674178e-01],
        [ 9.9803799e-01, -5.8300879e-02, -2.2827482e-02],
        [ 6.2606096e-02,  9.2490643e-01,  3.7500489e-01]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.03044816,  0.07330841,  0.99684453],
        [ 0.0528536 ,  0.9957936 , -0.07484547],
        [ 0.998138  , -0.05496572, -0.02644547]], dtype=float32)>)